version: "3.8"
services:
  server:
    build: ./server
    image: server
    container_name: server
    network_mode: host
    ports:
      - 8080:8080
    depends_on:
      - tf-db
    volumes:
      - ./server:/usr/src/app

  tf-db:
    image: mysql:8.0
    container_name: tf-db
    network_mode: host
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 111111
      MYSQL_DATABASE: tf
      TZ: Asia/Seoul
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
